---
- name: Configure SELinux on Debian-based system (Pre-Reboot)
  hosts: localhost
  become: true
  tasks:

    - name: Install SELinux packages
      apt:
        name:
          - selinux-basics
          - selinux-policy-mls
          - auditd
          - policycoreutils
          - selinux-utils
        state: present
        update_cache: yes

    - name: Activate SELinux
      command: selinux-activate
      register: selinux_activate_result
      ignore_errors: yes
